# Source: cluster-api-aws/templates/job-check.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: 2d81e325-ef3a-47dd-95e5-89b276d3ba4f-capi-aws-check
  namespace: 2d81e325-ef3a-47dd-95e5-89b276d3ba4f
spec:
  template:
    metadata:
      name: 2d81e325-ef3a-47dd-95e5-89b276d3ba4f-capi-aws
    spec:
      serviceAccountName: 2d81e325-ef3a-47dd-95e5-89b276d3ba4f-capi-aws
      containers:
      - name: wait-for-ready
        image: "ghcr.io/openinfradev/python_kubectl_argo:v1.1.0"
        imagePullPolicy: IfNotPresent
        command:
        - timeout 
        - 5m
        - /wait_for_kubeconfig.sh  
        - 2d81e325-ef3a-47dd-95e5-89b276d3ba4f
        - 2d81e325-ef3a-47dd-95e5-89b276d3ba4f
        volumeMounts:
        - name: vol
          subPath: wait_for_kubeconfig.sh
          mountPath: /wait_for_kubeconfig.sh
      volumes:
      - name: vol
        configMap:
          name: 2d81e325-ef3a-47dd-95e5-89b276d3ba4f-capi-aws
          defaultMode: 0555
      restartPolicy: OnFailure
